services:
  db:
    image: mysql:8.0
    container_name: cinematch_db
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db:/docker-entrypoint-initdb.d:ro

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: cinematch_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      APP_PORT: 8080
    volumes:
      - backend_node_modules:/app/backend/node_modules
    depends_on:
      - db
    ports:
      - "${APP_PORT}:8080"
    command: ["sh", "-c", "wait-for-it.sh db:3306 -- npm run start"]

volumes:
  db_data:
  backend_node_modules:
